name: articles
recipe: laravel
config:
  webroot: .public
  php: 7.4
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
    - database
  node:
    type: node:14
    build:
      - npm install
tooling:
  npm:
    service: node
  node:
    service: node